stages:
  pipeline:
    cmd: python3 src/Regression_script.py 
    deps:
    - data
    - src
    params:
      - n_neighbors
      - random_state
      - n_splits
      - test_size
    outs:
     - model_name.pickle
    metrics:
    - metrics.json:
        cache: false
    plots:
    - plots_file.json:
        cache: false