name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

      - name: install requirements
        run: |
          pip install -r requirements.txt

      - name: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull

      - name: dvc repro
        run: |
          dvc repro

      - name: metrics diff
        run: |
          git fetch --prune
          dvc metrics diff --show-md master > report.md

      - name: unit tests
        run: |
          python unit_tests.py
          
      - name: pylint treshold   
        run: |
          pylint --fail-under 9 src/train_model.py
          pylint --fail-under 9 src/feature_importance.py
          pylint --fail-under 9 src/Preparation.py
          pylint --fail-under 9 unit_tests.py