name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

      - name: install requirements
        run: |
          pip install -r requirements.txt

      - name: install dvc[gdrive]
        run: |
          pip install cryptography==35.0
          pip install httplib2==0.15.0
          pip install dvc[gdrive]

      - name: dvc pull
        run: |
          dvc pull

      - name: dvc repro
        run: |
          dvc repro

      - name: metrics diff
        run: |
          git fetch --prune
          dvc metrics diff --show-md master > report.md

      - name: unit tests
        run: |
          python unit_tests.py
      - name: metrics treshold   
        run: |
          pylint --fail-under=0.9 src/train_model.py
        