name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - run: |
          pip install -r requirements.txt
          dvc repro
          
          # git fetch --prune
          # dvc metrics diff --show-md master > report.md

          unit_tests.py
          
          pylint --fail-under=0.9 train_model.py
        