name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt

          npm i -g @dvcorg/cml
          
          sudo apt-get install -y \
            libcairo2-dev libfontconfig-dev \
            libgif-dev libjpeg-dev libpango1.0-dev librsvg2-dev
          npm install -g vega-cli vega-lite

          dvc pull
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add feature importance plot and metrics to the report
          echo "Validation results"
          cml-send-comment report.md
          # cml-publish FI_plot.png --md >> report.md

      - name: unit tests
        run: |
          python unit_tests.py
          
      - name: pylint treshold   
        run: |
          pylint --fail-under 9 src/train_model.py
          pylint --fail-under 9 src/feature_importance.py
          pylint --fail-under 9 src/Preparation.py
          pylint --fail-under 9 unit_tests.py